# Create samba private dir

d /run/samba 0755 _samba _samba -
d /var/cache/samba 0755 _samba _samba -
d /var/lib/samba 0755 _samba _samba -
d /var/lib/samba/private 0750 _samba _samba -
d /var/log/samba 0755 _samba _samba -
